matrix:
  include:
    - language: python
      python: 3.6.2
      services:
        - docker
      install:
        - pip install -r server/requirements.txt
      before_script:
        cd server/
      script:
        python3 -m pytest
      after_success: bash ./deploy.sh
    
    - language: node_js
      node_js: node
      before_install:
        cd client/
      script:
        npm test
      after_success:
        npm run deploy
  
  branches:
    only:
      - master