matrix:
  include:
    - language: python
      python: 3.6.2
      install:
        - pip install -r server/requirements.txt
      before_script:
        cd server/
      script:
        python3 -m pytest
    
    - language: node_js
      node_js: node
      install:
        - npm install
      before_script:
        cd client/
      script:
        npm test
  
  branches:
    only:
      - master