matrix:
  include:
  - language: python
    python: 3.6.2
    services:
    - docker
    install:
    - pip install -r server/requirements.txt
    before_script: cd server/
    script: python3 -m pytest
    after_success: bash ./deploy.sh
  - language: node_js
    node_js: node
    before_install:
      - cd client && openssl aes-256-cbc -K $encrypted_b496c556179a_key -iv $encrypted_b496c556179a_iv -in id_rsa.enc -out id_rsa -d
    script: npm test
    after_success:
      - npm run gh-pages-travis
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="build"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="id_rsa"
    - GIT_NAME="gilmoreg"
    - GIT_EMAIL="gilmoreg@live.com"
branches:
  only:
    - master
  except:
    - gh-pages
