version: '3'

services:
  db:
    image: postgres:9.6.5-alpine
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./server
    volumes:
      - $PWD/server:/src
    ports:
      - 5000:5000
    depends_on:
      - db

  # Node environment for building React
  webpack:
    build: ./client
    volumes:
      - $PWD/client:/src

  # ngnix server to serve static files
  website:
    image: nginx:mainline-alpine
    volumes:
      # Map build output of webpack container to nginx root
      - $PWD/client/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  pgdata: