version: '3'

services:
  db:
    image: postgres:9.6.5-alpine
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.6.12-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbit

  api:
    build:
      context: ./server
      dockerfile: $PWD/server/Dockerfile.dev
    env_file:
      - ./server/server.env
    volumes:
      - $PWD/server:/src
    ports:
      - 5000:5000
    depends_on:
      - db
      - rabbit

  celery_worker:
    build:
      context: ./server
      dockerfile: $PWD/server/Dockerfile.worker
    env_file:
      - ./server/server.env
    volumes:
      - $PWD/server:/src
    depends_on:
      - db
      - rabbit

volumes:
  pgdata: