version: '3'

services:
  db:
    image: postgres:9.6.5-alpine
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: $PWD/server/Dockerfile.dev
    env_file:
      - ./server/server.env
    volumes:
      - $PWD/server:/src
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  pgdata: