service: serverless

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ADMIN: ${file(env.yml):ADMIN}
    SECRET: ${file(env.yml):SECRET}
    API_URL: ${file(env.yml):API_URL}

region: us-west-1

functions:
  update:
    handler: handler.update
    events:
      - schedule: rate(6 hours)
