"""empty message

Revision ID: 8e550411d438
Revises: 
Create Date: 2017-09-24 00:43:43.242873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e550411d438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocklevels',
    sa.Column('stocklevel_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('stock_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stocklevel_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watches',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('added', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('set_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    op.drop_table('users')
    op.drop_table('stocklevels')
    # ### end Alembic commands ###
